admin_pages/urls.py
"""Defines url patterns for the admin_pages app."""

from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = 'admin_pages'

urlpatterns = [
    path('', views.admin_index, name='admin_index'),
    path('manage_site_look/', views.manage_site_look, name='manage_site_look'),
    path('manage_home/', views.manage_home, name='manage_home'),
    path('manage_about/', views.manage_about, name='manage_about'),
    path('manage_leadership/', views.manage_leadership, name='manage_leadership'),
    path('manage_leadership_header/', views.manage_leadership_header, name='manage_leadership_header'),
    path('manage_resources/', views.manage_resources, name='manage_resources'),
    path('manage_sermons_header/', views.manage_sermons_header, name='manage_sermons_header'),
    path('manage_worship_music_header/', views.manage_worship_music_header, name='manage_worship_music_header'),
    path('manage_worship_videos_header/', views.manage_worship_videos_header, name='manage_worship_videos_header'),
    path('manage_services/', views.manage_services, name='manage_services'),
    path('manage_contact/', views.manage_contact, name='manage_contact'),
    path('manage_seo/', views.manage_seo, name='manage_seo'),
    path('manage_users/', views.manage_users, name='manage_users'),
    path('manage_email_account/', views.manage_email_account, name='manage_email_account'),
    path('manage_ip_nolog_list/', views.manage_ip_nolog_list, name='manage_ip_nolog_list'),
    path('manage_email_denylist/', views.manage_email_denylist, name='manage_email_denylist'),

    path('new_leader/', views.new_leader, name='new_leader'),
    path('edit_leader/<int:leader_id>', views.edit_leader, name='edit_leader'),
    path('delete_leader/<int:leader_id>', views.delete_leader, name='delete_leader'),

    path('new_speaker/', views.new_speaker, name='new_speaker'),
    path('edit_speaker/<int:speaker_id>/', views.edit_speaker, name='edit_speaker'),
    path('confirm_delete_speaker/<int:speaker_id>/', views.confirm_delete_speaker, name='confirm_delete_speaker'),
    path('delete_speaker/<int:speaker_id>/', views.delete_speaker, name='delete_speaker'),

    path('new_artist/', views.new_artist, name='new_artist'),
    path('edit_artist/<int:artist_id>/', views.edit_artist, name='edit_artist'),
    path('confirm_delete_artist/<int:artist_id>/', views.confirm_delete_artist, name='confirm_delete_artist'),
    path('delete_artist/<int:artist_id>/', views.delete_artist, name='delete_artist'),

    path('new_sermon/<int:speaker_id>/', views.new_sermon, name='new_sermon'),
    path('edit_sermon/<int:sermon_id>/', views.edit_sermon, name='edit_sermon'),
    path('delete_sermon/<int:sermon_id>/', views.delete_sermon, name='delete_sermon'),

    path('new_song/<int:artist_id>/', views.new_song, name='new_song'),
    path('edit_song/<int:song_id>/', views.edit_song, name='edit_song'),
    path('delete_song/<int:song_id>/', views.delete_song, name='delete_song'),

    path('new_worship_video/<int:speaker_id>/', views.new_worship_video, name='new_worship_video'),
    path('edit_worship_video/<int:video_id>/', views.edit_worship_video, name='edit_worship_video'),
    path('delete_worship_video/<int:video_id>/', views.delete_worship_video, name='delete_worship_video'),

    path('new_nolog_ip/', views.new_nolog_ip, name='new_nolog_ip'),
    path('edit_nolog_ip/<int:nologip_id>/', views.edit_nolog_ip, name='edit_nolog_ip'),
    path('delete_nolog_ip/<int:nologip_id>/', views.delete_nolog_ip, name='delete_nolog_ip'),

    path('new_denylistemail/', views.new_denylistemail, name='new_denylistemail'),
    path('edit_denylistemail/<int:denylistemail_id>/', views.edit_denylistemail, name='edit_denylistemail'),
    path('delete_denylistemail/<int:denylistemail_id>/', views.delete_denylistemail, name='delete_denylistemail'),
]

api/urls.py
"""Defines url patterns for the api app."""

from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = 'api'

# Update which pages are allowed when app starts.
views.update_pages_allowed()

urlpatterns = [
    path('views/charts/', views.views_charts_today, name='views_charts_today'),
    path('views/charts/<str:enddate>', views.views_charts_enddate, name='views_charts_enddate'),
    path('views/charts/export_views/', views.export_views, name='export_views'),
    path('views/data/delete/<str:time_period>/<str:enddate>', views.delete_views, name='delete_views'),
    path('visitors/charts/', views.visitors_charts_today, name='visitors_charts_today'),
    path('visitors/charts/<str:enddate>', views.visitors_charts_enddate, name='visitors_charts_enddate'),
    path('visitors/charts/export_visitors/', views.export_visitors, name='export_visitors'),
    path('visitors/data/delete/<str:time_period>/<str:enddate>', views.delete_visitors, name='delete_visitors'),
    path('views/data/daily/<str:enddate>/', login_required(views.DailyPageViews.as_view())),
    path('views/data/weekly/<str:enddate>/', login_required(views.WeeklyPageViews.as_view())),
    path('views/data/monthly/<str:enddate>/', login_required(views.MonthlyPageViews.as_view())),
    path('visitors/data/daily/<str:enddate>/', login_required(views.DailyVisitors.as_view())),
    path('visitors/data/weekly/<str:enddate>/', login_required(views.WeeklyVisitors.as_view())),
    path('visitors/data/monthly/<str:enddate>/', login_required(views.MonthlyVisitors.as_view())),
]

lrbc_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    #path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('admin_pages/', include('admin_pages.urls')),
    path('api/', include('api.urls')),
    path('', include('site_pages.urls')),
    path('users/', include('users.urls')),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            template_name='users/reset_password.html'), name='password_reset_confirm'),
    path('reset_password_done', auth_views.PasswordResetDoneView.as_view(
            template_name='users/reset_password_sent.html'), name='password_reset_done'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
            template_name='users/reset_password_complete.html'), name='password_reset_complete'),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
]

templates/admin_pages/manage_resources/speakers/confirm_delete_speaker.html
{% extends "../../admin_pages_base.html" %}

{% block content %}

<div class="form-container">
	<div class="text-center"><h2>Delete Speaker</h2></div>
	<p>
		Deleting speaker {{ speaker.name }} will delete all of
		{{ speaker.name }}'s sermons and worship videos! Are you
		sure you wish to delete this speaker?
	</p>
	<div class="form-btn-container">
		<span class="space-left">
			<button class="btn btn-primary" onclick="javascript:history.back();">
				Cancel
			</button>
		</span>
		<span class="space-left">
			<a href="{% url 'admin_pages:delete_speaker' speaker.id %}">
				<button class="btn btn-danger">
					Delete
				</button>
			</a>
		</span>
	</div>
</div>

{% endblock content %}

templates/admin_pages/manage_resources/speakers/edit_speaker.html
{% extends "../../admin_pages_base.html" %}

{% block content %}

<div class="form-container">
	<div class="text-center title-container"><h2>Edit Speaker</h2></div>

	<form action="{% url 'admin_pages:edit_speaker' speaker.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<div class="form-btn-container">
			<span class="space-left-sm">
				<button class="btn btn-primary" type="submit">
					Save
				</button>
			</span>
			<span class="space-left">
				<button class="btn btn-danger" onclick="javascript:history.back();">
					Cancel
				</button>
			</span>
		</div>
	</form>
</div>
<br>

{% endblock content %}

templates/admin_pages/manage_resources/speakers/new_speaker.html
{% extends "../../admin_pages_base.html" %}

{% block content %}

<div class="form-container">
	<div class="text-center title-container"><h2>Add a new Speaker</h2></div>

	<form method='post' enctype='multipart/form-data'>
		{% csrf_token %}
		{{ form.as_p }}
		<div class="form-btn-container">
			<span class="space-left-sm">
				<button class="btn btn-primary" type="submit">
					Save
				</button>
			</span>
			<span class="space-left">
				<button class="btn btn-danger" onclick="javascript:history.back();">
					Cancel
				</button>
			</span>
		</div>
	</form>
</div>
<br>

{% endblock content %}